#!/bin/bash

# NVR napi mantés a mozgás video fájlokról
# cron.d: */5 * * * *   root   /usr/local/bin/seccam_serv

d=`pwd`

cd /home/video/SecCam

filename=nvr.run
process=`pgrep motion`

if test -f "$filename"; then
    if [ "$process" == "" ]; then
	motion 2>>/dev/null >>/dev/null
    fi
else
    pkill motion 2>>/dev/null >>/dev/null
    #echo "$process exists."
    #kill $process
fi

cd $d
