#!/bin/bash

# NVR napi mantés a mozgás video fájlokról
# cron.d: */5 * * * *   root   /usr/local/bin/seccam_serv

d=`pwd`

cd /home/video/SecCam

filename=nvr.run
timefilename=time.run
process=`pgrep motion`
night="21:00"
morning="06:00"

date

if test -f "$filename"; then
	start=true
	if test -f "$timefilename"; then
		start=false
		day=$(date +%u)
		rule=""
		x=0
		while read line; do
			x=$(( x+1 ))
			if [ $x -eq "$day" ]; then
				break
			fi
		done < $timefilename
		arrIN=(${line//-/ })
		t1=`date --date=${arrIN[0]} '+%s'`
		t2=`date --date=${arrIN[1]} '+%s'`
		t3=${arrIN[2]}
		now=`date +"%H:%M"`
		n0=`date --date=$now '+%s'`
		# test n0=`date --date=22:12 '+%s'`
		if [ "$n0" -gt "$t1" ] && [ "$n0" -lt "$t2" ]; then
			start=true
			echo "Megadott intervallumban vagyunk"
		else
			echo "Megadott intervallumon kívül vagyunk"
		fi
		if [ "$t3" == "X" ]; then
			echo "Éjszaka engdélyezve"
			e1=`date --date=$night '+%s'`
			e2=`date --date=$morning '+%s'`
			if [ "$n0" -gt "$e1" ] || [ "$n0" -lt "$e2" ]; then
				start=true
				echo " - éjszaka van"
			else
				echo " - nincs éjszaka"
			fi
		fi
	fi
	if [ $start ] ; then
		if [ "$process" == "" ]; then
			motion 2>>/dev/null >>/dev/null
			echo "Rögzítés indítása"
		else
			echo "Rögzítés már fut"
		fi
	fi
else
	echo "Rögzítés leállítása"
	pkill motion 2>>/dev/null >>/dev/null
	#echo "$process exists."
	#kill $process
fi

cd $d
