#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése
#

ut=`pwd`
cd /usr/local/bin

# helyi gép
d=`date`
echo "$d Helyi gép mentése." >> /var/log/sbackup.log
./backup-system 2>>/dev/null

# egyéb forrás
d=`date`
echo "$d Távoli gép (RPi) mentése." >> /var/log/sbackup.log
./backup-pi 2>>/dev/null

# mysql
d=`date`
echo "$d MySQL adatbázisok mentése." >> /var/log/sbackup.log
./backup-mysql 2>>/dev/null

# mentés felhőbe, adathordozóra
d=`date`
echo "$d Mentés adathordozóra, felhőbe." >> /var/log/sbackup.log
./backup-usb-mount 2>>/dev/null
./backup-rclone 2>>/dev/null

# mentés hálózati meghajtóra
d=`date`
 echo "$d Mentés hálózati meghajtóra." >> /var/log/sbackup.log
./backup-net-copy 2>>/dev/null

d=`date`
echo "$d Kész." >> /var/log/sbackup.log

cd $ut

#
