#!/bin/sh
#
# SBackup - rendszer
#
# Beállítások
#

# indítási könyvtár
TPATH=`pwd`

# modulok engedélyezése: 0 - letiltva, 1 - engedélyezve
ENABLE_SYSTEM=1
ENABLE_DAYROTATE=1
ENABLE_LOG=1
ENABLE_MAIL=1
ENABLE_WEBDL=1
ENABLE_RCLONE=1
ENABLE_SQL=1
ENABLE_USB=1
ENABLE_NETWORK=1

# a program helye
BINDIR="/usr/local/bin"

# logok
LOGDIR="/var/log"
LOGFILE="sbackup.log"
LOGARCHFILE="sbackup.log.1 sbackup.log.2 sbackup.log.3"

# log rotáció - a héten belüli nap száma: 1-7, 0 - letiltva
LOGROTATEDAY=5

# mentés helye
LOCALBACKUPDIR="/usr/local/share/backup"

# mentés előző napok
OLDDAY="d-1 d-2 d-3"

# mentésre jelölt könyvtárak
SYSDIRTOSAVE="/etc /var/www /usr/local/bin /var/lib/mysql"
USERDIRTOSAVE=".config .local Dokumentumok public_html"

# egyedi felhasználói könyvtárak $HOME könyvtárba
BACKUPDIRFILE=".backupdir"

# pi eszközön lévő mentésfájlok
WEBDOWNLOAD="https://192.168.102.200/backup"
WEBFILES="pi-etc.tar.gz pi-sql.tar.gz pi-web.tar.gz pi-bin.tar.gz"

# SQL adatbázisok helye
SQLDIR="/var/lib/mysql"

# rclone konfiguráció a felhős mentéshez
RCLONETARGET="google:/Mentés"

# USB-n lévő fájl neve, ha van ilyen, akkor arra megy a mentés
USBFILENAME=".backupusb"

# hálózati mentési hely SMB kapcsolathoz
NETHOST="192.168.1.100"
NETUSER="admin"
NETPASSWORD="Valami"
NETTARGET="/mnt/backupdir"

#
