#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése
#

d=`dirname $0`
. $d/backup-config

cd $LOCALBACKUPDIR

ldir=`ls -A /home`

for f in $SYSDIRTOSAVE; do
	f2=`basename $f`
	if [ -f $DEVICENAME-system-$f2.tar.gz ]; then
		rm $DEVICENAME-system-$f2.tar.gz 2>/dev/null
	fi
	tar rf $DEVICENAME-system-$f2.tar $f 2>/dev/null >>$LOGDIR/$LOGFILE
	gzip ./$DEVICENAME-system-$f2.tar 2>/dev/null
done

if [ $ENABLE_WEBDIR = 1 ]; then
	for x in $ldir; do
		if (test -d "/home/$x/.config/chromium/Default/File System"); then
			rm -r  "/home/$x/.config/chromium/Default/File System" 2>/dev/null
		fi
		for f in $USERDIRTOSAVE; do
			f2=`echo $f | tr -d '.'`
			if [ -f $DEVICENAME-$x-$f2.tar.gz ]; then
				rm $DEVICENAME-$x-$f2.tar.gz 2>/dev/null
			fi
			tar -rf $DEVICENAME-$x-$f2.tar --exclude=chromium /home/$x/$f 2>/dev/null >>$LOGDIR/$LOGFILE
			gzip ./$DEVICENAME-$x-$f2.tar 2>/dev/null
		done
		if (test -f /home/$x/$BACKUPDIRFILE); then
			for i in `cat /home/$x/$BACKUPDIRFILE`; do
				if [ -f $DEVICENAME-$x-$i.tar.gz ]; then
					rm $DEVICENAME-$x-$i.tar.gz 2>/dev/null >/dev/null
				fi
				tar -rf $DEVICENAME-$x-$i.tar --exclude=chromium /home/$x/$i 2>/dev/null >>$LOGDIR/$LOGFILE
				gzip -f ./$DEVICENAME-$x-$i.tar 2>/dev/null
			done
		fi
	done
fi

cd $TPATH

#
