#!/bin/sh
#
# SBackup - MySQL/MariaDB
#
# Adatbázisok mentése
#
#

. ./backup-config

cd $LOCALBACKUPDIR

mysqldump --all-databases >sqldb-all.sql 2>>$LOGFILE

# egyessével az adatbázisok:
#
# mysqldump mysql > mysql.sql
# mysqldump phpmyadmin> phpmyadmin.sql
mysqldump mysql >sqldb-mysql.sql 2>>$LOGFILE

cd $PATH

#
