#!/bin/sh
#
# SBackup - rendszer
#
# Log rotáció
#
#

. ./backup-config

if (test -f $LOGDIR/$LOGFILE); then
	for b in $OLDLOG; do
		c="$b $c"
	done
	for b in $c; do
		if test -z "$n"; then
			if (test -f "$LOGDIR/$b"); then
				rm $LOGDIR/$b 2>>/dev/null
			fi
		else
			mv $LOGDIR/$b $LOGDIR/$n 2>>/dev/null
		fi
		n=$b
	done
	mv $LOGDIR/$LOGFILE $LOGDIR/$b 2>>/dev/null
fi

touch $LOGDIR/$LOGFILE 2>>/dev/null

#
