#!/bin/sh
#
# SBackup - rendszer
#
# Felhasználók levelezésének mentése
#

d=`dirname $0`
. $d/backup-config

cd $LOCALBACKUPDIR

ldir=`ls -A /home`


for x in $ldir; do
	if [ -d /home/$x/Maildir ]; then
		rm $x-Maildir.tar.gz 2>&1 >>/dev/null
		tar -rf $x-Maildir.tar /home/$x/Maildir 2>>/dev/null >>$LOGDIR/$LOGFILE
		gzip ./$x-Maildir.tar 2>>$LOGDIR/$LOGFILE >>/dev/null
	fi
	if [ -d /home/$x/mail ]; then
		rm $x-mail.tar.gz 2>&1 >>/dev/null
		tar -rf $x-mail.tar /home/$x/mail 2>>/dev/null >>$LOGDIR/$LOGFILE
		gzip ./$x-mail.tar 2>>$LOGDIR/$LOGFILE >>/dev/null
	fi
	if [ -d /var/mail ]; then
		rm var-mail.tar.gz 2>&1 >>/dev/null
		tar -rf var-mail.tar /var/mail 2>>/dev/null >>$LOGDIR/$LOGFILE
		gzip ./var-mail.tar 2>>$LOGDIR/$LOGFILE >>/dev/null
	fi
done

cd $TPATH

#
