#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - mentés hálózati meghajtóra
#

. ./backup-config

if ping -c 1 -W 1 "$NETHOST" >>/dev/null; then
	echo $NETHOST létezik
	mount //$NETHOST/backupdir /mnt -o username=admin,password=Ki0 2>>$LOGFILE

	if [ -d $NETTARGET ]; then
		d=`date`
	else
		mkdir $NETTARGET 2>>/dev/null
	fi

	cp $LOCALBACKUPDIR/* $NETTARGET 2>>$LOGFILE
	mount /mnt 2>>$LOGFILE
fi

#
