#!/bin/sh
#
# SBackup - log rotáció
#
# Log rotáció
#
#

. ./backup-config

if (test -f $LOGFILE); then
	if (test -f $OLDLOG3); then
		rm $OLDLOG3 2>>/dev/null
	fi
	if (test -f $OLDLOG2); then
		mv $OLDLOG2 $OLDLOG3 2>>/dev/null
	fi
	if (test -f $OLDLOG1); then
		mv $OLDLOG1 $OLDLOG2 2>>/dev/null
	fi
	mv $LOGFILE $OLDLOG1 2>>/dev/null
fi

touch $LOGFILE 2>>/dev/null

#
