#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - RaspberryPi mentés web szerverről
#

. ./backup-config

if wget $WEBDOWNLOAD --timeout 10 -O - 2>>/dev/null; then
    cd $LOCALBACKUPDIR
    rm pi*.tar.gz 2>>/dev/null >>/dev/null

    for x in $WEBFILES; do
	#echo $WEBDOWNLOAD/$x
	wget -q --no-check-certificate $WEBDOWNLOAD/$x 2>>$LOGFILE
    done
    cd $TPATH
fi

#
