#!/bin/sh
#
# SBackup - MySQL/MariaDB
#
# Adatbázisok mentése:
#
#

ur=`pwd`
cd /usr/local/share/backup 2>>/var/log/sbackup.log

mysqldump --all-databases >sqlalldb.sql

# egyessével az adatbázisok:
#
# mysqldump mysql > mysql.sql
# mysqldump phpmyadmin> phpmyadmin.sql

cd $ut

#
