#!/bin/sh
#
# SBackup - rendszer
#
# Mentések rotációja
#
#

d=`dirname $0`
. $d/backup-config

cd $LOCALBACKUPDIR

for b in $OLDDAY; do
	c="$b $c"
done
for b in $c; do
	if test -z "$n"; then
		if [ -d $b ]; then
			rm $b/*.tar* 2>/dev/null
		else
			mkdir $b 2>/dev/null
		fi
	else
		if [ -d $n ]; then
			rm $n/*.tar* 2>/dev/null
		else
			mkdir $n 2>/dev/null
		fi
		mv $b/*.tar* $n 2>/dev/null
	fi
	n=$b
done
if [ -d $b ]; then
	rm $b/*.tar* 2>/dev/null
else
	mkdir $b 2>/dev/null
fi
mv *.tar* $b 2>/dev/null

cd $TPATH

#
