#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - rclone gdrive-ba
#

ur=`pwd`
cd /usr/local/share/backup 2>>/var/log/sbackup.log

li=`ls -a *.tar.gz`

for x in $li; do
	rclone copy $x google:/Mentés 2>>/var/log/sbackup.log
done

cd $ut