#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - rclone gdrive-ba
#

. ./backup-config

cd $LOCALBACKUPDIR

li=`ls -a *.tar.gz *.sql`

for x in $li; do
	rclone copy $x $RCLONETARGET 2>>$LOGFILE
done

cd $PATH

#
