#!/bin/sh
#
# SBackup - rendszer
#
# Beállítások
#

PATH=`pwd`

BINDIR=/usr/local/bin

LOGFILE=/var/log/sbackup.log
OLDLOG1=/var/log/sbackup.log.1
OLDLOG2=/var/log/sbackup.log.2
OLDLOG3=/var/log/sbackup.log.3

LOCALBACKUPDIR=/usr/local/share/backup

BACKUPFILE=.backupconf
BACKUPDIRFILE=.backupdir
BACKUPETCFILE=/etc/backup

WEBDOWNLOAD=https://192.168.10.200/backup

RCLONETARGET="google:/Mentés"

USBFILENAME=".backupusb"

NETHOST=192.168.1.1
NETTARGET=/mnt/backupdir

#
