#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - USB eszköz keresése, adatok mentése
#

. ./backup-config

e=`cat /proc/partitions | grep sd | awk '{print $4}' | grep -v sda | grep [123456789]`

for x in $e; do
    mkdir /media/$x >>/dev/null 2>>$LOGFILE
    /bin/mount /dev/$x /media/$x >>/dev/null 2>>$LOGFILE
done

./backup-usb-copy
#sleep 10
#sync

for x in $e; do
    /bin/umount /media/$x >>/dev/null 2>>$LOGFILE
    rmdir /media/$x >>/dev/null 2>>$LOGFILE
done

#
