#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - mentés letöltése web szerverről
#

d=`dirname $0`
. $d/backup-config

cd $LOCALBACKUPDIR

if [ "$WEBDLUSER" = "" ]; then
	WUSER=" "
else
	WUSER=" --user=$WEBDLUSER --password=$WEBDLPASSWD "
fi

if wget $WEBDOWNLOAD $WUSER --no-check-certificate -q --timeout 10 --spider 2>/dev/null; then
	for x in $WEBFILES; do
		#echo $WEBDOWNLOAD/$x
		if [ -f $x ]; then
			rm $x 2>/dev/null
		fi
		wget $WUSER -q --no-check-certificate $x 2>>$LOGDIR/$LOGFILE
	done
fi

for x in $WEBBACKUPSITES; do
	if wget $x $WUSER --no-check-certificate -q --timeout 10 --spider 2>/dev/null; then
		y=`echo $x | rev | cut -d'/' -f1 | rev`
		if [ -f $y ]; then
			rm $y 2>/dev/null
		fi
		#echo $x
		wget $WUSER -q --no-check-certificate $x 2>>$LOGDIR/$LOGFILE
	fi
done

cd $TPATH

#
