#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése
#

. ./backup-config
cd $BINDIR

# helyi gép
d=`date`
echo "$d Helyi gép mentése." >> $LOGFILE
./backup-system 2>>/dev/null

# egyéb forrás
d=`date`
echo "$d Távoli gép (RPi) mentése." >> $LOGFILE
./backup-pi 2>>/dev/null

# mysql
d=`date`
echo "$d MySQL adatbázisok mentése." >> $LOGFILE
./backup-mysql 2>>/dev/null

# mentés felhőbe, adathordozóra
d=`date`
echo "$d Mentés adathordozóra, felhőbe." >> $LOGFILE
./backup-usb-mount 2>>/dev/null
./backup-rclone 2>>/dev/null

# mentés hálózati meghajtóra
d=`date`
 echo "$d Mentés hálózati meghajtóra." >>  $LOGFILE
./backup-net-copy 2>>/dev/null

d=`date`
echo "$d Kész." >>  $LOGFILE

cd $PATH

#
