#!/bin/sh
#
# SBackup - rendszer
#
# Adatbázisok mentése
#
#

d=`dirname $0`
. $d/backup-config

if [ -d $SQLDIR ]; then
	cd $LOCALBACKUPDIR
	rm sql.tar.gz 2>>/dev/null

	# egyszrre az összes adatbázis
	# mysqldump --all-databases >sqldb-all.sql 2>>$LOGFILE
	#
	# egyessével az adatbázisok:
	# mysqldump mysql > mysql.sql
	# mysqldump phpmyadmin> phpmyadmin.sql
 	for x in $SQLDIR/*; do
	if [ -d $x ]; then
		y="${x##*/}"
		if [ $y != "performance_schema" ]; then
			mysqldump $y >sqldb-$y.sql 2>>$LOGDIR/$LOGFILE
	 	fi
	fi
	done

	tar cvvfz sql.tar.gz *.sql >>/dev/null 2>>/dev/null
	rm *.sql 2>>/dev/null
	cd $TPATH
fi

#

