#!/bin/sh
#
# SBackup - rendszer
#
# Beállítások
#

# indítási könyvtár
TPATH=`pwd`

# a program helye
BINDIR="/usr/local/bin"

# logok
LOGDIR="/var/log"
LOGFILE="sbackup.log"
OLDLOG="sbackup.log.1 sbackup.log.2 sbackup.log.3"

# mentés helye
LOCALBACKUPDIR="/usr/local/share/backup"

# mentés előző napok
OLDDAY="d-1 d-2 d-3"

# az egyes konfigurációk
BACKUPFILE=".backupconf"
BACKUPDIRFILE=".backupdir"
BACKUPETCFILE="/etc/backup"

# pi eszközön lévő mentésfájlok
WEBDOWNLOAD="https://192.168.102.200/backup"
#WEBFILES[0]="pi-etc.tar.gz"
#WEBFILES[1]="pi-sql.tar.gz"
#WEBFILES[2]="pi-web.tar.gz"
#WEBFILES[3]="pi-bin.tar.gz"
WEBFILES="pi-etc.tar.gz pi-sql.tar.gz pi-web.tar.gz pi-bin.tar.gz"

# SQL adatbázisok helye
SQLDIR="/var/lib/mysql"

# rclone konfiguráció a felhős mentéshez
RCLONETARGET="google:/Mentés"

# USB-n lévő fájl neve
USBFILENAME=".backupusb"

# hálózati mentési hely SMB kapcsolathoz
NETHOST="192.168.1.100"
NETTARGET="/mnt/backupdir"

#
