#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - RaspberryPi mentés web szerverről
#

ut=`pwd`

cd /usr/local/share/backup 2>>/var/log/sbackup.log
rm pi*.tar.gz 2>>/var/log/sbackup.log

wget -q --no-check-certificate https://192.168.10.200/backup/pi-etc.tar.gz 2>>/var/log/sbackup.log
wget -q --no-check-certificate https://192.168.10.200/backup/pi-web.tar.gz 2>>/var/log/sbackup.log
wget -q --no-check-certificate https://192.168.10.200/backup/pi-sql.tar.gz 2>>/var/log/sbackup.log
wget -q --no-check-certificate https://192.168.10.200/backup/pi-bin.tar.gz 2>>/var/log/sbackup.log

cd $ut

#
