#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - RaspberryPi mentés web szerverről
#

d=`dirname $0`
. $d/backup-config

if wget $WEBDOWNLOAD --timeout 10 -O - 2>/dev/null; then
	cd $LOCALBACKUPDIR

	for x in $WEBFILES; do
		#echo $WEBDOWNLOAD/$x
		if [ -f $xz ]; then
			rm $x 2>/dev/null
		fi
		wget -q --no-check-certificate $WEBDOWNLOAD/$x 2>>$LOGDIR/$LOGFILE
	done

	cd $TPATH
fi

#
